apiVersion: v1
kind: Service
metadata:
  name: calculation-service
  labels:
    run: calculation-service
spec:
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
  selector:
    run: calculation-service