apiVersion: v1
kind: Service
metadata:
  name: main-processor
  labels:
    run: main-processor
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    run: main-processor