apiVersion: v1
kind: Service
metadata:
  name: ground-data-core
  labels:
    run: ground-data-core
spec:
  ports:
  - port: 8004
    targetPort: 8004
    protocol: TCP
  selector:
    run: ground-data-core