apiVersion: v1
kind: Service
metadata:
  name: openaq-adapter
  labels:
    run: openaq-adapter
spec:
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    run: openaq-adapter