apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: climate-management-kafka
spec:
  kafka:
    config:
      auto.create.topics.enable: false
      log.message.format.version: "2.6.0"
      log.retention.bytes: 1073741824
      log.retention.hours: 1
      log.retention.check.interval.ms: 300000
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
      message.max.bytes: 104857600
      max.request.size: 104857600
      producer.max.request.size: 104857600
      consumer.max.request.size: 104857600
      socket.receive.buffer.bytes: 104857600
      socket.send.buffer.bytes: 104857600
      max.partition.fetch.bytes: 104857600
      socket.request.max.bytes: 104857600
    listeners:
      external:
        type: nodeport
        tls: false
      plain: {}
      tls: {}
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 1
    resources: {}
    storage:
      deleteClaim: false
      size: 4Gi
      type: persistent-claim
    version: 2.6.0
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 1
    resources: {}
    storage:
      deleteClaim: false
      size: 4Gi
      type: persistent-claim