apiVersion: v1
kind: Service
metadata:
  name: air-pollution-ui
  labels:
    run: air-pollution-ui
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000 
    protocol: TCP
  selector:
    run: air-pollution-ui