apiVersion: v1
kind: Service
metadata:
  name: main-db-external-svc
spec:
  selector:
    app: main-db-svc
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: client
      port: 27017
      targetPort: 27017
      nodePort: 30318
      protocol: TCP